//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertMe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlertMe.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine address location. Please try again later..
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppMenuItemAbout {
            get {
                return ResourceManager.GetString("AppMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Apps.
        /// </summary>
        public static string AppMenuItemMoreApps {
            get {
                return ResourceManager.GetString("AppMenuItemMoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string AppMenuItemOptions {
            get {
                return ResourceManager.GetString("AppMenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1 Name.
        /// </summary>
        public static string Contact1Name {
            get {
                return ResourceManager.GetString("Contact1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2 Name.
        /// </summary>
        public static string Contact2Name {
            get {
                return ResourceManager.GetString("Contact2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown Time.
        /// </summary>
        public static string CountdownTime {
            get {
                return ResourceManager.GetString("CountdownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Countdown.
        /// </summary>
        public static string EnableCountdown {
            get {
                return ResourceManager.GetString("EnableCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable your location services by going to Settings -&gt; Location -&gt; Turn on Location Services option..
        /// </summary>
        public static string GPSDisabled {
            get {
                return ResourceManager.GetString("GPSDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial number of sent text has expired (.
        /// </summary>
        public static string InitialTrial1 {
            get {
                return ResourceManager.GetString("InitialTrial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ). To extend trial for another .
        /// </summary>
        public static string InitialTrial2 {
            get {
                return ResourceManager.GetString("InitialTrial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  texts please rate app..
        /// </summary>
        public static string InitialTrial3 {
            get {
                return ResourceManager.GetString("InitialTrial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My location is: .
        /// </summary>
        public static string MyLocationIs {
            get {
                return ResourceManager.GetString("MyLocationIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertMe Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Arm.
        /// </summary>
        public static string PlayAlarm {
            get {
                return ResourceManager.GetString("PlayAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  Please purchase app for unlimitted texts..
        /// </summary>
        public static string PleasePurchase {
            get {
                return ResourceManager.GetString("PleasePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent TextCount.
        /// </summary>
        public static string SentTextCount {
            get {
                return ResourceManager.GetString("SentTextCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not sent.  Error = .
        /// </summary>
        public static string TextNotSentError {
            get {
                return ResourceManager.GetString("TextNotSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial number of texts allowed to be sent is .
        /// </summary>
        public static string TrialMessage {
            get {
                return ResourceManager.GetString("TrialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Text Sent: .
        /// </summary>
        public static string TrialTextSent {
            get {
                return ResourceManager.GetString("TrialTextSent", resourceCulture);
            }
        }
    }
}
